export const ROOT_PATH = "/"
export const INFO_PATH = "/info"
export const JOGS_PATH = "/jogs"
export const TRACK_PATH = "/track"
export const UPDATE_JOG_PATH_ID = "/update/:id"
export const UPDATE_JOG_PATH = "/update/"
export const ABOUT_US_PATH = "/aboutUs"
export const INVALID_PATH = "*"
