export const BASE_URL = "https://jogtracker.herokuapp.com/api/v1/auth"
// export const LOGIN = "LOGIN"
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"
// export const LOGOUT_USER = "LOGOUT_USER";
// export const LOGIN_ERROR = "LOGIN_ERROR";
// export const RECOVERY_SENT = "PASSWORD_SENT";
// export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
// export const CLOSE_PASSWORD_RECOVERY = "CLOSE_PASSWORD_RECOVERY";
// export const RECOVERY_ERROR = "RECOVERY_ERROR";
// export const REGISTER_ERROR = "REGISTER_ERROR";
// export const CHANGE_INFO = "CHANGE_INFO";
// export const CHANGE_INFO_ERROR = "CHANGE_INFO_ERROR";
// export const RESET_LOGIN_ERRORS = "RESET_LOGIN_ERRORS";
