export const ADD_JOG = "@@api/ADD_JOG"
export const ADD_JOG_SUCCESS = "@@api/ADD_JOG_SUCCESS"
export const ADD_JOG_ERROR = "@@api/ADD_JOG_ERROR"
export const GET_JOGS = "@@api/GET_JOGS"
export const GET_JOGS_SUCCESS = "@@api/GET_JOGS_SUCCESS"
export const GET_JOGS_ERROR = "@@api/GET_JOGS_ERROR"
export const CLEAR_JOGS = "CLEAR_JOGS"
